
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  springboot-app:
    build: .
    container_name: springboot_container
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8000:80"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongodb:27017/Exerciseplanner
    volumes:
      - .:/app  # Mounts your local code inside the container

volumes:
  mongo_data:
